version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - '8080:8080'
    environment:
      JAVA_OPTS: '-Dkeycloak.profile.feature.account_api=enabled'
  gateway:
    build: ./api/gateway
    ports:
      - 8080:3000
    env_file:
      - ./api/gateway/.env
    depends_on:
      - gateway
    networks:
      - public
      - private
  memploi:
    build: ./api/memploi
    ports:
      - 8081:3001
    env_file:
      - ./api/memploi/.env
    depends_on:
      - gateway
      - users
    networks:
      - private
  users:
    build: ./api/users
    ports:
      - 8082:3002
    env_file:
      - ./api/users/.env
    depends_on:
      - gateway
    networks:
      - private
networks:
  public:
    driver: bridge
  private:
    driver: bridge
