apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: default
spec:
  secretName: example-tls-secret
  issuerRef:
    name: letsencrypt-prod  # Use the name of your Issuer or ClusterIssuer
    kind: ClusterIssuer     # Adjust based on whether you're using an Issuer or ClusterIssuer
  dnsNames:
    - memploi.com