package com.hist.BysApp.entities.enums;

public enum CEvent {
  APPOINTEMENT, MEETING, FETE, CONGE, JOUR_FERIE,ACTIVITE_PARA_SCOLAIRE,ACTIVITE_SCOLAIRE, ACTIVITE_PARA_SCOLAIRE_HEBDOMADAIRE,ACTIVITE_PARA_SCOLAIRE_MENSUELLE,ACTIVITE_PARA_SCOLAIRE_ANNUELLE,
  ACTIVTE_SCOLAIRE_JOURNALIER, ACTIVTE_SCOLAIRE_HEBDOMADAIRE, ACTIVTE_SCOLAIRE_MENSUELLE,  ACTIVTE_SCOLAIRE_ANNUELLE
}
