package com.hist.BysApp.entities.enums;

public enum TYPE_NOT {
	FORGET_PASS,
	NEW_USER,
	NEW_PAYMENT,
	NEW_PAYROLL,
	NEW_BOARD_UPDATE,
	NEW_ONLINE_COURSES,
	MESSAGE,
	WELCOME,
	BROADCAST_TO_PROF,
	BROADCAST_TO_PERS,
	BROADCAST_TO_STUDENT,
	BROADCAST_TO_All,
}
