apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-memploi-deployment
  labels:
    app: ui-memploi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app:  ui-memploi
  template:
   metadata:
     labels:
       app:  ui-memploi
   spec:
     containers:
     - name:  ui-memploi
       image: pledika/ui-memploi
       ports:
        - containerPort: 80
       env:
       - name: NODE_ENV
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-ui-memploi
             key: NODE_ENV
       - name: PORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-ui-memploi
             key: PORT
       - name: SERVICE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-ui-memploi
             key: SERVICE_NAME

---
apiVersion: v1
kind: Service
metadata:
  name:  ui-memploi-service
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "2c11d3de-035d-483d-bba1-0fe0c7af72fe"
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "65"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "932680d8-03b0-4d65-b849-9bb6f64f2cbf"
spec:
  type: LoadBalancer
  selector:
    app: ui-memploi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80