apiVersion: v1
kind: ConfigMap
metadata: 
  name: monkata-configmap
data : 
 
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: lolo91
  KEYCLOAK_JWT_URI: http://keycloak-service:8083/realms/master/protocol/openid-connect/certs
  # EUREKA
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8070/eureka/ 
  EUREKA_HOST : http://eureka-service
  EUREKA_PORT  :  '8070'
  EUREKA_PATH  :  /eureka/apps/

  # SESSION
  SESSION_SECRET  :  ad0554000d85103f1a7be322a6d95e895ff5c14d4cbd870247e41248824e2a66
  
  #GATEWAY @
  GATEWAY_URL  :  http://gateway-service:3000
  # KEYCLOAK 
  KEYCLOAK_REALM : Monkata
  KEYCLOAK_AUTH_SERVER_URL : http://keycloak-service:7878
  KEYCLOAK_SERVER_URL : http://keycloak-service:7878
  KEYCLOAK_SSL_REQUIRED : external
  KEYCLOAK_RESOURCE : users-client
  KEYCLOAK_RESOURCE_LOGIN : jobs-app-fe
  KEYCLOAK_SECRET : uIORJLhptgXBgDn6ZicY17LMd0TrID0n
  KEYCLOAK_CONFIDENTIAL_PORT  :  "0"
  KEYCLOAK_PUBLIC_KEY : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2U7DKTEKuS0zDDdjuC5hpFmN+e4yLijzvErTVxYKC4n0Iy+JqTb5UmF+i8REAODQZbUErP7Gsb/xmTcAr73GyvYO/HB3wB4599rBashS2Ruov+YJARqLlbUTrTe+sHyi/tiJMGHnHgAIQuW7R26tMuwRuYkPt7g6Do+Y9bU5Ra5qBqzWLmlH7WWKupswxYvl1zxZBA+ytRDUUfco0WKjc8N/X7CtDAbUyhVZysNZ+40gfaLkznX3UWHB4ztYlidz/bdR+NyO0bejt305/eL7DE26SgDoyEJnYcIhZaxp+A9zgHwVSTe+q7vQe8wMrXe/krwM+tjQBb8GZZDagPC2UQIDAQAB
    
  