apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: keycloak
  template:
   metadata:
     labels:
       app: keycloak
   spec:
     containers:
     - name: keycloak
       image: quay.io/keycloak/keycloak:22.0.1
       ports:
        - containerPort: 8080 
        
       env:
       - name: JAVA_OPTS
         value: -Dkeycloak.profile.feature.account_api=enabled
       - name: KEYCLOAK_ADMIN
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key: KEYCLOAK_ADMIN 
             
       - name: KEYCLOAK_ADMIN_PASSWORD
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap
             key:  KEYCLOAK_ADMIN_PASSWORD
---       
apiVersion: v1
kind: Service 
metadata: 
  name: keycloak-service
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 8080