apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: eureka
  template:
   metadata:
     labels:
       app: eureka
   spec:
     containers:
     - name: eureka
       image: pledika/mkt-eureka
       ports:
        - containerPort: 8070
---       
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "03d3d1d9-0dd4-47e2-8b34-09f410f43d7a"
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "65"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "8070"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "0855a031-e7cc-43f6-aa95-0f59af50962b"
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070