apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app:  gateway
  template:
   metadata:
     labels:
       app:  gateway
   spec:
     containers:
     - name:  gateway
       image: pledika/mkt-gateway
       ports:
        - containerPort: 3000
       envFrom:
        - configMapRef:
            name: monkata-configmap
       env:
       - name: NODE_ENV
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: NODE_ENV
       - name: PORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: PORT
       - name: SERVICE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: SERVICE_NAME
       - name: HOST
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: HOST
       - name: IP
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: IP
           
---       
apiVersion: v1
kind: Service
metadata:
  name:  gateway-service
spec:
  selector:
    app:  gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000