apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app:  gateway
  template:
   metadata:
     labels:
       app:  gateway
   spec:
     containers:
     - name:  gateway
       image: pledika/mkt-gateway
       ports:
        - containerPort: 3000
       envFrom:
        - configMapRef:
            name: monkata-configmap
       env:
       - name: NODE_ENV
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: NODE_ENV
       - name: PORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: PORT
       - name: SERVICE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: SERVICE_NAME
       - name: HOST
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: HOST
       - name: IP
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: IP
           
---
kind: Service
apiVersion: v1
metadata:
  name: gateway-service
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "d012d867-b389-4c96-b76b-6cc0ebc40545"
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "65"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "80"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "27c22c2e-73c6-4e58-b60b-3e5c9659725a"
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000