apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app:  gateway
  template:
   metadata:
     labels:
       app:  gateway
   spec:
     containers:
     - name:  gateway
       image: pledika/mkt-gateway
       ports:
        - containerPort: 3000
       envFrom:
        - configMapRef:
            name: monkata-configmap
       env:
       - name: DEV
         value: "1"
       - name: NODE_ENV
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: NODE_ENV
       - name: PORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: PORT
       - name: SERVICE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: SERVICE_NAME
       - name: HOST
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: HOST
       - name: IP
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-gw
             key: IP
           
---
kind: Service
apiVersion: v1
metadata:
  name: gateway-service
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "20634e8b-73c5-4fea-99a0-96a89b5b1ee3"
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "65"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "eb7004be-bb83-4b3d-8094-9459adad52d8"
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000