apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1 
  selector:
    matchLabels:
      app:  users
  template:
   metadata:
     labels:
       app:  users
   spec:
     containers:
     - name:  users
       image: pledika/mkt-users
       ports:
        - containerPort: 3002
       envFrom:
        - configMapRef:
            name: monkata-configmap
       env:
       - name: NODE_ENV
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: NODE_ENV
       - name: PORT
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: PORT
       - name: SERVICE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: SERVICE_NAME
       - name: HOST
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: HOST
       - name: IP
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: IP
       - name: DB_DATABASE_NAME
         valueFrom: 
           configMapKeyRef:
             name: monkata-configmap-users
             key: DB_DATABASE_NAME
---       
apiVersion: v1
kind: Service
metadata:
  name:  users-service
spec:
  selector:
    app:  users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002