name: AUTH_UI_BUILD
on:
  push:
    branches:
      - dev
    paths:
      - 'ui/memploi/**'
jobs:
  builds:
    runs-on: ubuntu-latest
    environment: Monkata
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OC_TOKEN: ${{ secrets.OC_TOKEN }}
      IMAGE_NAME: ${{ vars.UIEMPLOI_IMAGE }}
      CLUSTER: ${{ vars.CLUSTER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install  Deps
        working-directory: ui/memploi
        run: npm install --force

      - name: Build MEMPLOI
        working-directory: ui/memploi
        run: npm run build --force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/

      - name: Log in to Docker Hub # Docker Login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the docker image for #Eureka
        working-directory: ui/memploi # Change this to your pom.xml directory
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.OC_TOKEN }}
          run: |
            doctl kubernetes cluster kubeconfig save 0a6946a5-edc3-414b-afff-1f19885c54ec
            kubectl rollout restart deployment ui-memploi-deployment
