name: Build_Gateway
on:
  pull_request:
    paths:
      - 'api/gw/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/gw && npm install && npm run build
