name: Build_Users
on:
  pull_request:
    paths:
      - 'api/users/**'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/users && npm install && npm run build
