name: EMPLOI_UI_BUILD

on:
  push:
    branches:
      - dev
    #paths:
    #- 'ui/memploi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Monkata
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OC_TOKEN: ${{ secrets.OC_TOKEN }}
      IMAGE_NAME: ${{ secrets.UIEMPLOI_IMAGE }} # Updated to use secrets instead of vars
      CLUSTER: ${{ secrets.CLUSTER }} # Updated to use secrets instead of vars

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use Node.js version compatible with your application

      - name: Install Dependencies
        working-directory: ui/memploi
        run: npm install --force

      - name: Build MEMPLOI
        working-directory: ui/memploi
        run: npm run build --force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ui/memploi/dist/

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        working-directory: ui/memploi
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.OC_TOKEN }}
          run: |
            doctl kubernetes cluster kubeconfig save $CLUSTER
            kubectl rollout restart deployment ui-memploi-deployment
