name: AUTH_UI_BUILD
on:
  push:
    branches:
      - dev
    paths:
      - 'ui/auth/**'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build  EMPLOI
        working-directory: ui/auth
        run: npm install && npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/ # Replace with your build output directory
