name: Build Spring Boot Eureka App

on:
  push:
    branches:
      - main
    paths:
      - 'api/eureka/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Monkata
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OC_TOKEN: ${{ secrets.OC_TOKEN }}
      EUREKA_IMAGE_NAME: ${{ vars.EUREKA_IMAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: api/eureka # Change this to your pom.xml directory
        run: mvn clean package

      - name: Archive the build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: api/eureka/target/*.jar # Change this to your target directory

      - name: Log in to Docker Hub # Docker Login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the docker image for #Eureka
        working-directory: api/eureka # Change this to your pom.xml directory
        run: docker build -t $EUREKA_IMAGE_NAME .

      - name: Push Docker image
        run: docker push $EUREKA_IMAGE_NAME

      - name: Digital Ocean
        uses: digitalocean/action-doctl@v3
        with:
          token: ${{ secrets.OC_TOKEN }}
          run: doctl kubernetes cluster kubeconfig save 0a6946a5-edc3-414b-afff-1f19885c54ec
          -run: kubectl rollout restart deployment eureka-deploy
