name: Build_Eureka
on:
  pull_request:
    paths:
      - 'api/eureka/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/eureka && mvn clean && mvn install && mvn build
