name: Build_Emploi
on: pull_request

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/emploi && npm install && npm i nodemailer && npm run build
