name: Build_Emploi
on:
  pull_request:
    paths:
      - 'api/emploi/**'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/emploi && npm install && npm i --save-dev @types/nodemailer && npm run build
