name: EMPLOI_UI_BUILD
on:
  push:
    branches:
      - dev
    paths:
      - 'ui/memploi/**'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify your Node.js version
      - name: Install  Deps
        working-directory: ui/memploi
        run: npm install --force

      - name: Build AUTH
        working-directory: ui/memploi
        run: npm run build --force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/ # Replace with your build output directory
