name: Build_Admin
on: pull_request

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./api/admin && npm install && npm i --save-dev @types/nodemailer  && npm run build
