name: ConfigMap
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Monkata
    env:
      CLUSTER: ${{ vars.CLUSTER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up K8s
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create Kubernetes configmap
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERS_NAME: ${{ vars.USERS_DB_NAME }}
          DB_EMPLOI_NAME: ${{ vars.EMPLOI_DB_NAME }}
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service/eureka/
          EUREKA_HOST: eureka-service
          EUREKA_PORT: '8070'
          EUREKA_PATH: /eureka/apps/
          SESSION_SECRET: ad0554000d85103f1a7be322a6d95e895ff5c14d4cbd870247e41248824e2a66
          GATEWAY_URL: gateway-service
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

        run: |
          cat <<EOF > monkata-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: monkata-configmap
          data:
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_USERS_NAME: "${DB_USERS_NAME}"
            DB_EMPLOI_NAME: "${DB_EMPLOI_NAME}"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}"
            EUREKA_HOST: "${EUREKA_HOST}"
            EUREKA_PORT: "${EUREKA_PORT}"
            EUREKA_PATH: "${EUREKA_PATH}"
            SESSION_SECRET: "${SESSION_SECRET}"
            GATEWAY_URL: "${GATEWAY_URL}"
            PUBLIC_KEY: "${PUBLIC_KEY}"
            DEV: "1"
          EOF
      - name: Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.OC_TOKEN }}

      - name: Apply Kubernetes configmap
        run: |
          doctl kubernetes cluster kubeconfig save $CLUSTER 
          kubectl apply -f monkata-configmap.yaml
