name: CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file to Auth
        run: cp ui/.htaccess ui/auth/dist/listee-angular

      - name: Copy file to Memploi
        run: cp ui/.htaccess ui/memploi/dist/listee-angular
